name: KAiWaMemo
options:
  deploymentTarget:
    iOS: 16.0
targets:
  KAiWaMemo:
    type: application
    platform: iOS
    sources:
      - path: KAiWaMemo/KAiWaMemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.KAiWaMemo
        GENERATE_INFOPLIST_FILE: YES